//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenKO_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_USER
    {
        public int Id { get; set; }
        public string strAccountID { get; set; }
        public string strPasswd { get; set; }
        public string strSocNo { get; set; }
        public string strEmail { get; set; }
        public byte strAuthority { get; set; }
        public System.DateTime PremiumExpire { get; set; }
        public int sQuestionId { get; set; }
        public string sQuestionAnswer { get; set; }
        public int CountryId { get; set; }
    }
}
