//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenKO_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNews
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string nContent { get; set; }
        public bool Status { get; set; }
        public int TypeId { get; set; }
        public int cUserID { get; set; }
        public System.DateTime cDate { get; set; }
        public Nullable<int> eUserID { get; set; }
        public Nullable<System.DateTime> eDate { get; set; }
    }
}
