//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by N3ME.rc
//
#define ID_MODIFY_DTEX_MIRROR           3
#define IDC_GROUP                       3
#define ID_MODIFY_DTEX_CW90D            4
#define ID_MODIFY_DTEX_CW180D           8
#define ID_MODIFY_DTEX_CW270D           9
#define IDD_ABOUTBOX                    100
#define IDD_BROWSE_PATH                 102
#define IDD_BASE                        103
#define IDR_MAINFRAME                   128
#define IDR_N3METYPE                    129
#define IDD_SCENE_GRAPH                 130
#define IDD_SELECT                      131
#define IDD_FOLDER_SELECT               134
#define IDC_MOVE                        136
#define IDC_ROTATE                      137
#define IDC_ZOOM                        138
#define IDC_TRANSFORM                   139
#define IDD_BRUSH                       140
#define IDB_SCENE_NODES                 142
#define IDD_TERRAINSIZE                 143
#define IDC_LOAD                        144
#define IDD_SETDETAILTEXTURE            145
#define IDD_INPUT_ATTR                  146
#define IDD_INPUT_GROUP                 147
#define IDD_DEL_GROUP                   148
#define IDD_DTEX_GROUP                  149
#define IDD_RIVER_PROPERTY              150
#define IDD_ADDDTEX                     153
#define IDD_MODIFY_DTEX                 156
#define IDD_SET_LIGHTMAP                158
#define IDD_DELDTEX                     159
#define IDD_LOAD_TILESET                160
#define IDD_SAVE_NEW_TILESET            161
#define IDD_MAKE_NPCPATH                162
#define IDD_LOAD_NPCPATH                163
#define IDD_SAVE_NPCPATH                164
#define IDD_SOW_SEED                    165
#define IDD_MAKE_WALL                   166
#define IDD_EDIT_EVENT                  167
#define IDD_EDIT_EVENT_ATTR             168
#define IDD_POND_PROPERTY               169
#define IDD_LOAD_EVENT                  170
#define IDD_SAVE_EVENT                  171
#define IDD_UNUSED_FILES                172
#define IDD_MAKE_REGEN_USER             173
#define IDD_SHAPE_LIST                  174
#define IDD_EDIT_WARP                   175
#define IDD_SAVE_DIVIDE                 176
#define IDD_CONTROL_HEIGHT_SCALE        177
#define IDD_EDIT_BGM                    178
#define IDD_ADD_SOUNDGROUP              179
#define IDD_ALL_MAP_VIEW                181
#define IDD_LIGHT                       182
#define IDC_COMBO                       1000
#define IDC_SLIDER_ROTATE               1001
#define IDC_CB_PART_SHAPE               1001
#define IDC_FILELIST                    1001
#define IDC_EDIT_ROTATE                 1002
#define IDC_E_NAME                      1002
#define IDC_LP_TRANSFORM                1003
#define IDC_SYNCH_FOLDERS               1003
#define IDC_LP_SHAPE                    1004
#define IDC_LP_CHR                      1005
#define IDC_CB_LOD                      1006
#define IDC_CB_PART_CHARACTER           1007
#define IDC_LP_CAMERA                   1008
#define IDC_PREVIEW                     1008
#define IDC_LP_LIGHT                    1009
#define IDC_SHAPE                       1009
#define IDC_SLIDER_SIZE                 1010
#define IDC_LP_MATERIAL                 1010
#define IDC_SLIDER_FALLOFF              1011
#define IDC_CB_PLUG_CHARACTER           1011
#define IDC_EDIT_SIZE                   1012
#define IDC_STATIC_NAME                 1012
#define IDC_EDIT_FALLOFF                1013
#define IDC_EDIT1                       1013
#define IDC_LP_CHR_PART                 1013
#define IDC_COMBO_FILELIST              1014
#define IDC_LP_CHR_PLUG                 1014
#define IDC_EDIT_NAME                   1014
#define IDC_EDIT_AGREE                  1015
#define IDC_BTN_SAVE                    1016
#define IDC_EDIT_MONEY                  1016
#define IDC_TEXTUREVIEW                 1017
#define IDC_EDIT_ZONE                   1017
#define IDC_ATTR                        1018
#define IDC_EDIT_POS_X                  1018
#define IDC_COMBO_ATTR                  1019
#define IDC_EDIT_POS_Y                  1019
#define IDC_COMBO_GROUP                 1020
#define IDC_EDIT_POS_Z                  1020
#define IDC_EDIT_RAD                    1021
#define IDC_LIST_GROUP                  1022
#define IDC_BTN_ADDGROUP                1023
#define IDC_EDIT_INPUTGROUP             1024
#define IDC_BTN_DELGROUP                1024
#define IDC_LIST_DELGROUP               1026
#define IDC_TREE_DTEX_GROUP             1027
#define IDC_LP_RIVER                    1030
#define IDC_NOTSELECTED                 1031
#define IDC_BUTTON_EXTRUDE              1032
#define IDC_BUTTON_DELETE_VERTEX        1033
#define IDC_BTN_ADDDTEX                 1033
#define IDC_BUTTON_RECALC_UV            1034
#define IDC_ADDDTEXLIST                 1034
#define IDC_BTN_DELDTEX                 1034
#define IDC_BUTTON_DELETE_RIVER         1035
#define IDC_B_SET_PATH                  1035
#define IDC_B_SET_RESOURCE_PATH         1035
#define IDC_E_PATH                      1036
#define IDC_STATIC_TRANSFORM            1037
#define IDC_E_TRANSFORM_X               1038
#define IDC_E_TRANSFORM_Y               1039
#define IDC_TILEAUTO                    1039
#define IDC_E_TRANSFORM_Z               1040
#define IDC_TILEMANUEL                  1040
#define IDC_TILEMANUELNOMIX             1041
#define IDC_TREE_OBJ                    1047
#define IDC_PREVIEW_DTEX_GROUP          1052
#define IDC_LB_GROUP                    1053
#define IDC_SLIDER_DTEX                 1054
#define IDC_SLIDER_TILEREGION           1058
#define IDC_SLIDER_FARPLANE             1059
#define IDC_SLIDER_LIGHT                1060
#define IDC_LM_SLD_PEN_SIZE             1062
#define IDC_LM_SLD_DENSITY              1070
#define IDC_LM_SLD_HARD                 1071
#define IDC_LM_SLD_OPACITY              1072
#define IDC_RADIO1                      1074
#define IDC_RADIO2                      1075
#define IDC_LIST_DELDTEX                1077
#define IDC_BTN_LOAD_TILESET            1078
#define IDC_BTN_SAVE_TILESET            1079
#define IDC_BTN_SAVE_NEWNAME_TILESET    1080
#define IDC_STATIC_TILESETNAME          1081
#define IDC_LIST_LOAD_TILESET           1082
#define IDC_LIST_TILESET                1083
#define IDC_EDIT_NEWTILESETNAME         1084
#define IDC_COMBO_NPC                   1085
#define IDC_BUTTON_RECALCVERTEX         1085
#define IDC_EDIT_NUM_NPC                1086
#define IDC_BTN_RECORD                  1087
#define IDC_COMBO_NPC_ATTR_GROUP        1088
#define IDC_LIST_NPCPATH                1089
#define IDC_COMBO_NPC_ATTR_REGEN        1090
#define IDC_COMBO_NPC_ATTR_CREATE       1091
#define IDC_RDO_START_RGN               1093
#define IDC_RDO_MAKE_PATH               1094
#define IDC_BTN_LOAD_PATHSET            1095
#define IDC_BTN_SAVE_PATHSET            1096
#define IDC_PATHSETNAME                 1097
#define IDC_COMBO_ACTIONTYPE            1098
#define IDC_EDIT_REGENTIME              1099
#define IDC_RDO_MAKE_ACT_RGN            1100
#define IDC_LIST_NPCPATHFILENAME        1101
#define IDC_COMBO_NPC_OPTION            1101
#define IDC_EDIT_NPCPATHFILENAME        1102
#define IDC_BTN_SAVE_SERVER_PATHSET     1103
#define IDC_BTN_PATH_MODIFY             1105
#define IDC_BTN_PATH_DELETE             1106
#define IDC_STATIC_SELECTEDCOLOR        1107
#define IDC_BTN_SELECT_COLOR            1108
#define IDC_E_ZONEID                    1109
#define IDC_EDT_NPCPATHNAME             1110
#define IDC_CB_SEED                     1111
#define IDC_CB_TILEGROUP                1112
#define IDC_LB_SOWED                    1113
#define IDC_BTN_SOW                     1114
#define IDC_BTN_DEL_SEED                1115
#define IDC_NUM_POINT                   1116
#define IDC_LIST_WALL                   1117
#define IDC_BTN_WALL_RECORD             1118
#define IDC_BTN_WALL_EDIT               1119
#define IDC_BTN_DELETE                  1120
#define IDC_EDIT_WALL                   1121
#define IDC_EVENT_LIST                  1122
#define IDC_BTN_EVENT_RECORD            1123
#define IDC_BTN_EVENT_EDIT              1124
#define IDC_EDIT_EVENT_ATTR_TYPE        1124
#define IDC_BTN_EVENT_DEL               1125
#define IDC_EDIT_EVENT_ATTR_CON1        1125
#define IDC_EDIT_EVENT_ATTR_CON2        1126
#define IDC_EDIT_EVENT_ATTR_CON3        1127
#define IDC_EDIT_EVENT_ATTR_CON4        1128
#define IDC_EDIT_EVENT_ATTR_CON5        1129
#define IDC_EDIT_EVENT_ATTR_EXE1        1130
#define IDC_EDIT_EVENT_ATTR_EXE2        1131
#define IDC_EDIT_EVENT_ATTR_EXE3        1132
#define IDC_EDIT_EVENT_ATTR_EXE4        1133
#define IDC_EDIT_EVENT_ATTR_EXE5        1134
#define IDC_EDIT_EVENT_ATTR_ID          1135
#define IDC_STATIC_CURR_EVENT           1136
#define IDC_EDIT_EVENT_ATTR_NAME        1137
#define IDC_RDO_VIEW_NONMOVE            1138
#define IDC_RDO_VIEW_NONE               1139
#define IDC_CHECK_FLAT                  1140
#define IDC_BUTTON_DELETE_POND          1141
#define IDC_LP_POND                     1142
#define IDC_STATIC_GRASSINFO            1143
#define IDC_BTN_GRASSINFOLOAD           1144
#define IDC_BTN_SAVEGAME                1145
#define IDC_STATIC_CURR_FILENAME        1146
#define IDC_BTN_GRASS_DELETE            1146
#define IDC_BTN_LOAD_EVTFILE            1147
#define IDC_BTN_GRASSINFOSAVE           1147
#define IDC_BTN_SAVE_EVTFILE            1148
#define IDC_LIST_SAVED_EVT_FILE         1150
#define IDC_EDIT_NEW_EVT_FILE           1151
#define IDC_EDIT_EVENT_ZONE_ID          1152
#define IDC_STATIC_DTEXGROUP            1153
#define IDC_STATIC_GRASS                1154
#define IDC_BTN_GRASS_READ              1155
#define IDC_LIST_FILES                  1158
#define IDC_DELETE                      1159
#define ID_CANCEL                       1160
#define IDC_LIST_INVALID_OBJECTS        1161
#define IDC_FLAT_HEIGHT                 1162
#define IDC_RDO_GET_HEIGHT              1166
#define IDC_RDO_FLATEN                  1167
#define IDC_LIST_REGENUSERREGION        1168
#define IDC_BTN_SAVE_AS                 1169
#define IDC_EDT_PATHNAME                1170
#define IDC_BTN_SETCOLOR                1171
#define IDC_LIST_OBJ                    1173
#define IDC_BTN_SORT                    1174
#define IDC_LIST_WARP                   1177
#define IDC_BTN_UPDATE                  1179
#define IDC_BTN_EDIT                    1180
#define IDC_EDIT_ID                     1181
#define IDC_BTN_EXPORT                  1182
#define IDC_BTN_IMPORT                  1183
#define IDC_STC_TOTAL_SIZE              1183
#define IDC_CB_DIVISION                 1185
#define IDC_SLIDER1                     1186
#define IDC_STATIC_MINIMAP              1187
#define IDC_SLD_ATTEN                   1187
#define IDC_BTN_LOAD_NPCLIST            1188
#define IDC_EDT_TRANS_Z                 1192
#define IDC_BTN_TRANS                   1193
#define IDC_EDT_TRANS_X                 1194
#define IDC_LIST_SOUNDGROUP             1195
#define IDC_BTN_ADD_SOUNDGROUP          1196
#define IDC_LIST_SOUNDINFO              1197
#define IDC_BGM_NAME1                   1198
#define IDC_BGM_NAME2                   1199
#define IDC_BGM_NAME3                   1200
#define IDC_BGM_NAME4                   1201
#define IDC_BROWSE_TREE                 1202
#define IDC_BGM_REGENTIME1              1202
#define IDC_FOLDER_LIST                 1203
#define IDC_BGM_REGENTIME2              1203
#define IDC_TUNNEL_TREE                 1204
#define IDC_BGM_REGENTIME3              1204
#define IDC_BGM_REGENTIME4              1205
#define IDC_BGE_REGENTIME1              1206
#define IDC_BGE_REGENTIME2              1207
#define IDC_BGE_REGENTIME3              1208
#define IDC_BGE_REGENTIME4              1209
#define IDC_BGE_NAME1                   1210
#define IDC_BGE_NAME2                   1211
#define IDC_BGE_NAME3                   1212
#define IDC_BGE_NAME4                   1213
#define IDC_BTN_DELETE_SOUNDGROUP       1214
#define IDC_BTN_INPUT_INFO              1215
#define IDC_BTN_INPUT_INFO_EDIT         1216
#define IDC_BTN_INPUT_INFO_DEL          1217
#define IDC_BTN_MODIFY_SOUNDGROUP       1218
#define IDC_BTN_BGM_NAME1               1220
#define IDC_BTN_BGM_NAME2               1221
#define IDC_BTN_BGM_NAME3               1222
#define IDC_BTN_BGM_NAME4               1223
#define IDC_EDT_BGM_REGEN1              1224
#define IDC_EDT_BGM_REGEN2              1225
#define IDC_EDT_BGM_REGEN3              1226
#define IDC_EDT_BGM_REGEN4              1227
#define IDC_BTN_BGE_NAME1               1228
#define IDC_BTN_BGE_NAME2               1229
#define IDC_BTN_BGE_NAME3               1230
#define IDC_BTN_BGE_NAME4               1231
#define IDC_EDT_BGE_REGEN1              1232
#define IDC_EDT_BGE_REGEN2              1233
#define IDC_EDT_BGE_REGEN3              1234
#define IDC_EDT_BGE_REGEN4              1235
#define IDC_EDT_GROUPNAME               1236
#define IDC_BTN_DEL_BGM_NAME1           1237
#define IDC_BTN_DEL_BGM_NAME2           1238
#define IDC_BTN_LOAD_GROUP              1238
#define IDC_BTN_DEL_BGM_NAME3           1239
#define IDC_BTN_LOAD_REGEN              1239
#define IDC_BTN_DEL_BGM_NAME4           1240
#define IDC_BTN_DEL_BGE_NAME1           1241
#define IDC_BTN_LOAD_CREATE             1241
#define IDC_RADIO_SOW                   1241
#define IDC_BTN_DEL_BGE_NAME2           1242
#define IDC_BTN_LOAD_OPTION             1242
#define IDC_RADIO_SELECT                1242
#define IDC_BTN_DEL_BGE_NAME3           1243
#define IDC_SEED_EXIT                   1243
#define IDC_BTN_DEL_BGE_NAME4           1244
#define IDC_BUTTON_RANDOM               1244
#define IDC_S_TILE_DETAIL               1245
#define IDC_SOW_BRUSH_SIZE              1246
#define IDC_MAP_VIEW                    1247
#define IDC_MAP_UPDATA                  1248
#define IDC_MAP_VIEW_CANCEL             1249
#define IDC_BUTTON_EDITPOND             1249
#define IDC_BUTTON_MOVE_POND            1250
#define IDC_BUTTON_STATION_POND         1251
#define IDC_WIDTHLENGTH                 1252
#define IDC_HEIGHTLENGTH                1253
#define IDC_STATICNAME1                 1254
#define IDC_STATICNAME2                 1255
#define IDC_BU_RECALCUV                 1260
#define IDC_STATIC3                     1261
#define IDC_COMBO_GOPOND                1262
#define IDC_STATIC4                     1263
#define IDC_COMBO_RIBER                 1264
#define IDC_LIST_LIGHTS                 1265
#define IDC_BTN_DOWNLOAD                1267
#define IDC_BTN_UPLOAD                  1268
#define IDC_PATHNAME                    1269
#define IDC_EDT_NAME                    1270
#define IDC_STC_COLOR                   1271
#define IDC_SLD_RANGE                   1272
#define ID_CURSOR_SELECT                32774
#define ID_CURSOR_OBJ_BRUSH             32775
#define ID_EDIT_PROPERTY                32776
#define ID_FILLMODE_WIREFRAME           32777
#define ID_FILLMODE_SOLID               32778
#define ID_CURSOR_ROTATE                32779
#define ID_CURSOR_POS                   32780
#define ID_CURSOR_SCALE                 32781
#define ID_FILE_EXPORT                  32788
#define ID_VIEW_SOURCEOBJECT            32789
#define ID_VIEW_OUTPUTOBJECT            32790
#define ID_VIEW_WIREFRAME               32791
#define ID_VIEW_SOLID                   32792
#define ID_CURSOR_EDIT_TERRAIN          32794
#define ID_TIP_FOCUS_SELOBJ             32796
#define ID_TIP_FOCUS_ALL                32797
#define ID_TIP_DROP                     32798
#define ID_BUTTON32799                  32799
#define ID_TIP_DELETE_OBJ               32800
#define ID_CURSOR_SMOOTH_TERRAIN        32801
#define ID_FILE_IMPORT                  32802
#define ID_EDIT_DTEX                    32803
#define ID_VIEW_DTEX                    32804
#define ID_CURSOR_DTEX                  32805
#define ID_FILE_SERVER_DATA             32806
#define ID_CURSOR_EDIT_RIVER            32807
#define ID_PROJECT_SET                  32808
#define ID_FILE_COLORMAP_LOAD           32809
#define ID_FILE_COLORMAP_SAVE           32810
#define ID_FILE_GAMETILETEX_SAV         32811
#define ID_FILE_GAMETILETEX_SAVE        32811
#define ID_RESOURCE_PATH_SET            32812
#define ID_TIP_GENERATE_COLORMAP        32813
#define ID_TIP_TILING_ALL               32814
#define ID_TIP_GENERATE_COLORMAP_ALL    32816
#define ID_TIP_DEFAULT_MATERIAL         32817
#define ID_TIP_REMOVE_ALPHAFLAG         32818
#define ID_CURSOR_EDIT_LIGHTMAP         32819
#define ID_CURSOR_MAKE_NPCPATH          32821
#define ID_VIEW_SELECTED_OBJECT_WIREFRAME 32822
#define ID_TIP_SOW_SEED                 32823
#define ID_FILE_IMPORT_POST_DATA_FROM_SCENE 32824
#define ID_VIEW_HIDE_OBJ                32825
#define ID_VIEW_AXIS_AND_GRID           32826
#define ID_CURSOR_MAKE_WALL             32827
#define ID_CURSOR_EDIT_EVENT            32828
#define ID_FILE_IMPORT_SHAPES           32829
#define ID_CURSOR_EDIT_POND             32830
#define ID_FILE_IMPORT_HEIGHT           32831
#define ID_TIP_DELETE_UNUSED_FILES      32832
#define ID_TIP_DELETE_OVERLAPPED_OBJECTS 32833
#define ID_TIP_DELETE_SELECTED_SOURCE_OBJECTS 32834
#define ID_VIEW_ORTH                    32835
#define ID_CURSOR_FLAT_TERRAIN          32836
#define ID_VIEW_TOGGLE_FOG              32837
#define ID_CURSOR_REGEN_USER            32838
#define ID_TIP_SET_WARP_INFO            32839
#define ID_FILE_SAVE_DIVIDE             32840
#define ID_FILE_EXPORT_HEIGHT_BMP       32841
#define ID_FILE_IMPORT_HEIGHT_BMP       32842
#define ID_TIP_SET_HEIGHT_SCALE         32843
#define ID_CURSOR_SOUND                 32844
#define ID_SELECT_MAP_EDIT              32845
#define ID_CURSOR_LIGHTOBJ              32846

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        183
#define _APS_NEXT_COMMAND_VALUE         32847
#define _APS_NEXT_CONTROL_VALUE         1273
#define _APS_NEXT_SYMED_VALUE           107
#endif
#endif
