//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by N3CE.rc
//
#define IDD_ABOUTBOX                    100
#define ID_VIEW_ARRANGE                 127
#define IDR_MAINFRAME                   128
#define IDR_N3CETYPE                    129
#define IDD_ANIMATION                   130
#define IDD_TOOL                        131
#define IDD_FOLDER_SELECT               134
#define IDD_CHR_PROPERTY                138
#define IDB_N3BASE_NODES                140
#define IDC_B_MAKE_SMOOTH               1000
#define IDC_E_FRAME_START               1002
#define IDC_E_FRAME_END                 1003
#define IDC_E_FRAME_PER_SEC             1004
#define IDC_E_FRAME_CUR                 1005
#define IDC_E_JOINT_NAME                1006
#define IDC_SLD_SCENE_FRAME             1007
#define IDC_E_START_FRAME_PLUG_TRACE0   1008
#define IDC_E_FRAME_PLUG_TRACE_START    1008
#define IDC_E_END_FRAME_PLUG_TRACE0     1009
#define IDC_E_FRAME_PLUG_TRACE_END      1009
#define IDC_LP_MATERIAL                 1010
#define IDC_E_START_FRAME_PLUG_TRACE1   1010
#define IDC_E_FRAME_SOUND0              1010
#define IDC_E_END_FRAME_PLUG_TRACE1     1011
#define IDC_E_FRAME_SOUND1              1011
#define IDC_LP_PLUG                     1011
#define IDC_E_FRAME_BLEND0              1012
#define IDC_LP_FXPLUG_PART              1012
#define IDC_E_FRAME_BLEND1              1013
#define IDC_E_FRAME_STRIKE0             1014
#define IDC_TREE_CHR                    1015
#define IDC_E_FRAME_STRIKE1             1015
#define IDC_E_SCENE_FRM_END             1016
#define IDC_E_SCENE_FRM_START           1017
#define IDC_STATIC_HELP                 1017
#define IDC_B_ADD                       1018
#define IDC_CB_LOD                      1018
#define IDC_B_DELETE                    1019
#define IDC_B_SET_FRAME_START           1020
#define IDC_B_OPTIMIZE                  1021
#define IDC_B_OPTIMIZE_ANIMATION_DATA   1021
#define IDC_B_SET_FRAME_END             1022
#define IDC_E_NUMBER                    1023
#define IDC_B_SORT_ANIMATION            1024
#define IDC_B_OFFSET                    1024
#define IDC_B_APPLY_OFFSET_FRAME        1024
#define IDC_LIST_ANIMATION              1025
#define IDC_LIST_ANIMATION0             1025
#define IDC_E_ANI_NAME                  1026
#define IDC_B_LOAD                      1027
#define IDC_B_SET_START_FRAME_TRACE0    1028
#define IDC_B_SET_FRAME_PLUG_TRACE_START 1028
#define IDC_B_SET_END_FRAME_TRACE0      1029
#define IDC_B_SET_FRAME_PLUG_TRACE_END  1029
#define IDC_B_SET_START_FRAME_TRACE1    1030
#define IDC_B_SET_FRAME_SOUND0          1030
#define IDC_B_SET_END_FRAME_TRACE1      1031
#define IDC_B_SET_FRAME_SOUND1          1031
#define IDC_LIST_ANIMATION1             1032
#define IDC_CB_KEY_TYPE                 1033
#define IDC_LIST_ANIMATION2             1033
#define IDC_B_SET_FRAME_STRIKE0         1033
#define IDC_CB_ZOOM                     1034
#define IDC_LIST_ANIMATION3             1034
#define IDC_B_SET_FRAME_STRIKE1         1034
#define IDC_E_OFFSET                    1035
#define IDC_B_MOVE_UP                   1036
#define IDC_B_MOVE_DOWN                 1037
#define IDC_B_SAVE                      1038
#define IDC_SLIDER_FRM                  1039
#define IDC_E_BLEND_TIME                1040
#define IDC_B_SAVE_AS                   1040
#define IDC_SPIN_PROCESS_KEY            1041
#define IDC_LIST_SOUND                  1041
#define IDC_C_AXIS_X                    1042
#define IDC_B_ADD_TEST_SOUND            1042
#define IDC_LIST_SOUND1                 1042
#define IDC_C_AXIS_Y                    1043
#define IDC_B_NEW                       1043
#define IDC_B_DELETE_TEST_SOUND0        1043
#define IDC_C_AXIS_Z                    1044
#define IDC_E_ANI_FILE_NAME             1044
#define IDC_B_DELETE_TEST_SOUND1        1044
#define IDC_STATIC_GRAPH                1045
#define IDC_E_MOVE_SPEED                1045
#define IDC_B_INSERT                    1046
#define IDC_CB_SORT_METHOD              1047
#define IDC_STATIC_ANIMATION_TIME_SUM   1047
#define IDC_C_DELAYED_LOOPING           1048
#define IDC_B_CALCULATE_DELAY_TIME_WITH_UPPER_ANIMATION 1049
#define IDC_B_CALCULATE_DELAY_TIME_WITH_LOWER_ANIMATION 1050
#define IDC_C_DOUBLE_ATTACK             1051
#define IDC_B_ADD_TEST_SOUND0           1052
#define IDC_C_PLAY                      1053
#define IDC_B_ADD_TEST_SOUND1           1053
#define IDC_LIST_SOUND0                 1054
#define IDC_BROWSE_TREE                 1202
#define IDC_FOLDER_LIST                 1203
#define IDC_TUNNEL_TREE                 1204
#define ID_VIEW_XRAY                    32771
#define ID_VIEW_JOINT                   32772
#define ID_EDIT_CHR_PROPERTY            32773
#define ID_EDIT_PART_ADD                32774
#define ID_EDIT_PART_DELETE             32775
#define ID_EDIT_PLUG_ADD                32776
#define ID_EDIT_PLUG_DELETE             32777
#define ID_EDIT_CHR_JOINT_SET           32778
#define ID_EDIT_CHR_PART_ADD            32779
#define ID_EDIT_CHR_PART_DELETE         32780
#define ID_EDIT_CHR_PLUG_ADD            32781
#define ID_EDIT_CHR_PLUG_DELETE         32782
#define ID_EDIT_CHR_PART_SET            32784
#define ID_EDIT_CHR_PLUG_SET            32785
#define ID_FILE_SAVE_AS_ONE_FOLDER      32786
#define ID_FILE_SAVE_SELECTED           32787
#define ID_EDIT_CHR_PLUG_ROTATION_RESET 32788
#define ID_EDIT_ANIMATION_DATA_COPY     32789
#define ID_EDIT_ANIMATION_DATA_PASTE    32790
#define ID_EDIT_ANIMATION_DATA_MOVE_UP  32791
#define ID_EDIT_ANIMATION_DATA_MOVE_DOWN 32792
#define ID_EDIT_ANIMATION_DATA_ADD      32793
#define ID_EDIT_ANIMATION_DATA_INSERT   32794
#define ID_EDIT_ANIMATION_DATA_DELETE   32795
#define ID_EDIT_CHR_PLUG_ADDCLOAK       32796
#define ID_SOUND_FILE_ADD0              32797
#define ID_SOUND_FILE_ADD1              32798
#define ID_SOUND_DELETE0                32799
#define ID_SOUND_DELETE1                32800
#define ID_TOOL_OPTIMIZE_ANIMATION_DATA 32801
#define ID_EDIT_SET_VISIBLE             32802
#define ID_EDIT_CHR_PLUG_IMPORT_VMESH   32804
#define ID_EDIT_CHR_PLUG_IMPORT_PMESH   32805
#define ID_EDIT_FXPLUG_SET              32806
#define ID_EDIT_FXPLUG_DELETE           32808
#define ID_EDIT_FXPLUG_PART_ADD         32809
#define ID_EDIT_FXPLUG_PART_DELETE      32810
#define ID_EDIT_FXPLUG_STOP             32811
#define ID_EDIT_FXPLUG_START            32812

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        133
#define _APS_NEXT_COMMAND_VALUE         32813
#define _APS_NEXT_CONTROL_VALUE         1055
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
